### ISSUE TITLE
Overriding `--css-variables` in Anki

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/anki#78]
> Here's how custom properties [in the cascade](https://www.smashingmagazine.com/2019/07/css-custom-properties-cascade/#re-introducing-custom-properties) are scoped globally and locally.

So long as the specificity is correct (i.e: you're updating [CSS variables](https://caniuse.com/css-variables) on the correct global or local class, such as `:root` or `.selector`) simply change the CSS Variables at the end of the `main.css` document! <s>I don't _think_ that you can change `--css-variables` to override styles that have used that variable (i.e: `var(--css-variable)`) — although you may be able to if there's [greater specificity](https://stackoverflow.com/questions/53097662/why-css-variables-override-another-files-css-variable). The code below won't work as you might hope:</s>

**It's fairly easy to add a class to the main HTML `<tag>` element to [switch between themes](https://codepen.io/jdsteinbach/pen/ExeaPd).** I've tried this kind of setup Anki and it works:

```css
:root {
   /* The highlighting colours */
  --color-code-light-background: #ffffcc;
  --color-code-light-base: #586e75;
  --color-code-light-comment: #93a1a1;
  --color-code-light-error: #93a1a1;
  --color-code-light-highlight: #dc322f;
  --color-code-light-keyword: #859900;
  --color-code-light-lowlight: #268bd2;
  --color-code-light-number: #2aa198;
  --color-code-light-operator: #859900;
  --color-code-light-string: #2aa198;
  --color-code-light-variable: #268bd2;
}

/* They're used here, for example */
code,
kbd,
pre,
samp {
  ...
  background: var(--color-code-light-background);
}
```

You can override the styles at the bottom of the `main.css` document like this:

```css
:root {
  --color-code-light-background: blue;  /* Make me blue! */
}
```

You can even use a variable [before it's declared](https://codepen.io/smashingmag/pen/gNGdaO):

```css
p {
  color: var(--new-css-variable);
}

#inner {
  --new-css-variable: green;
}
```

### Before (default `--css-variables`)

<img width="837" alt="Screenshot 2023-12-03 at 18 55 32" src="https://github.com/badlydrawnrob/anki/assets/1176875/28a743bb-9e9d-4272-a5f8-52ad323e84d7">

### After (changing `--css-variables`)

<img width="835" alt="Screenshot 2023-12-03 at 18 56 18" src="https://github.com/badlydrawnrob/anki/assets/1176875/f21c89ff-5ed2-44dd-89bb-5174d5a51b67">

_Originally posted by @badlydrawnrob in https://github.com/badlydrawnrob/anki/issues/42#issuecomment-1834381594_
