### ISSUE TITLE
Twig code block: rendering {{ i }} incorrectly

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/anki#9]
As the only "Anki" solution is to wholesale replace `{{` with `<%` tags (which means [replacing every single one of them](https://anki.tenderapp.com/discussions/ankidesktop/15367-escape-field-tags-curly-brackets#comment_38341930)) it's probably best to use either images, regex or perhaps even css to render the tags properly.

- [Javascript version](http://stackoverflow.com/questions/413071/regex-to-get-string-between-curly-braces-i-want-whats-between-the-curly-brace)
- [CSS example](http://codepen.io/badlydrawnrob/pen/rOQBOR) using `<i class="{"></i>` (double `{{` doesn't work in the Anki browser for some reason)

**Comment by badlydrawnrob** [comment]
Adding a `helpers.less` with the [CSS example code](http://codepen.io/badlydrawnrob/pen/rOQBOR).

**Comment by badlydrawnrob** [comment]
```css
i[class^='{'],
i[class^='}'] {
  color: inherit;

  &::before {
    display: inline-block;
  }
}

i[class^='{']::before {
  content: '{{';
}

i[class^='}']::before {
  content: '}}';
}
```

Will now allow us to use `<i class="{{"></i>` and <i class="}}"></i>`, making it a little easier to remember the class name.
